### ISSUE TITLE
Discussion: Should the subscribe operator be a puller?

### ISSUE THREAD

**Issue by zebulonj** [zebulonj/callbag-subscribe#2]
I'm inclined to think that `callbag-subscribe` should pull as well as listen. It'd have no effect if the source is just listenable (not pullable), but would ensure that it's operable with [pullable sources](https://github.com/callbag/callbag/blob/master/getting-started.md#pullable).

**Comment by staltz** [comment]
Sounds reasonable. Pulling doesn't hurt in case the source is listenable, unless if you're really worried about performance in case of a busy listenable source, but even then the overhead would be negligible.
