### ISSUE TITLE
export `Dispose` type

### ISSUE THREAD

**Issue by warapitiya** [zebulonj/callbag-subscribe#9]
Currently `Dispose` type is not exported from TypeDefinition.

**Comment by zebulonj** [comment]
Either it is ([see here](https://github.com/zebulonj/callbag-subscribe/blob/835ac6ad87c9244cfdb8123fa80c0176aae3b9d2/index.d.ts#L15)) or I'm misunderstanding your request. Feel free to submit a pull request.

**Comment by zebulonj** [comment]
Closing this, since I haven't had a response. Feel free to re-open if you believe this is still an issue.
